#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=11

# This project keeps its real environment in .env.local, not .env.
ENV_FILE=".env.local"

OLD_HOST="crochette-zeta.vercel.app"
OLD_USER="ndnpro"
NEW_USER="yarnsandbuttons"
NEW_PROJECT="yarnsandbuttons"
OLD_PROJECT="crochette"
WANTED_HOST="yarnsandbuttons.vercel.app"

banner "Rename Crochette infrastructure to Yarns and Buttons"

# -- 1 ---------------------------------------------------------------------
stage "Preflight: confirm what is about to change"
say "Vercel account   $OLD_USER  ->  $NEW_USER"
say "Vercel project   $OLD_PROJECT  ->  $NEW_PROJECT"
say "Deployment host  $OLD_HOST  ->  $WANTED_HOST"
say "Preview links    <project>-<hash>-$OLD_USER.vercel.app"
say "             ->  <project>-<hash>-$NEW_USER.vercel.app"
printf '\n'
note "Preview URLs are built from the account slug and the project name, so"
note "stages 2 and 3 rewrite them as a side effect. Stage 10 proves that."
printf '\n'
note "Land the code PR first. The origin must already be env-driven, or the"
note "site keeps emitting the old host in its sitemap and every email link."
printf '\n'
step "Checking whether $WANTED_HOST is still unclaimed..."
_code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 15 "https://$WANTED_HOST" 2>/dev/null || echo "000")
if [[ "$_code" == "404" ]]; then
  say "  -> HTTP 404: unclaimed. Good."
elif [[ "$_code" == "000" ]]; then
  warn "Could not reach Vercel to check. Carry on, but read the name Vercel"
  warn "actually assigns in stage 3 rather than assuming."
else
  warn "HTTP $_code: something already answers on $WANTED_HOST."
  warn "Vercel will append a suffix. Stage 3 asks you to read the real one."
fi
printf '\n'
confirm "Proceed with the rename?" || { say "Nothing changed. Re-run when ready."; exit 0; }

# -- 2 ---------------------------------------------------------------------
stage "Vercel: rename the account"
warn "This releases the '$OLD_USER' slug and changes every URL for your"
warn "personal account, not only this project. Old dashboard links will 404."
printf '\n'
open_url "https://vercel.com/account"
step "Find the Username field in your account's General settings."
step "Change it from '$OLD_USER' to '$NEW_USER' and save."
note "If Vercel says the username is taken, pick another and remember it -"
note "it becomes part of your preview URLs, not the production host."
pause "Done? Press Enter."

# -- 3 ---------------------------------------------------------------------
stage "Vercel: rename the project"
say "The production hostname comes from the PROJECT name, not the account."
printf '\n'
open_url "https://vercel.com/dashboard"
step "Open the 'crochette' project, then Settings -> General."
step "Change the Project Name to 'yarnsandbuttons' and save."
step "Vercel now shows the project's production domain. READ IT."
printf '\n'
warn "Do not assume it is $WANTED_HOST. If the name was taken, Vercel appends"
warn "a suffix, exactly as it did to give you '$OLD_HOST'."
printf '\n'
ask NEXT_PUBLIC_SITE_URL "Paste the full production URL (https://...):"
NEXT_PUBLIC_SITE_URL="${NEXT_PUBLIC_SITE_URL%/}"
NEW_HOST="${NEXT_PUBLIC_SITE_URL#https://}"
say "Using origin: $NEXT_PUBLIC_SITE_URL"

# -- 4 ---------------------------------------------------------------------
stage "Vercel: pin the origin explicitly"
say "The code falls back to Vercel's own production-domain variable, so this"
say "is belt-and-braces - but it is also the value you will edit when the"
say "studio's own domain lands, so setting it now makes that a one-line move."
printf '\n'
open_url "https://vercel.com/dashboard"
step "Project -> Settings -> Environment Variables."
step "Add  NEXT_PUBLIC_SITE_URL  =  $NEXT_PUBLIC_SITE_URL"
step "Scope it to Production. Leave Preview and Development unset."
printf '\n'
note "While you are there, confirm 'Automatically expose System Environment"
note "Variables' is ON. That is what feeds the fallback."
write_env NEXT_PUBLIC_SITE_URL "$NEXT_PUBLIC_SITE_URL"
pause "Done? Press Enter."

# -- 5 ---------------------------------------------------------------------
stage "Google: authorise the new sign-in callback"
warn "Skip this and Google sign-in breaks the moment the host changes."
printf '\n'
open_url "https://console.cloud.google.com/apis/credentials"
step "Open your Web application OAuth 2.0 Client ID."
step "Under 'Authorised redirect URIs', ADD:"
say  "    $NEXT_PUBLIC_SITE_URL/api/auth/callback/google"
step "Under 'Authorised JavaScript origins', ADD:"
say  "    $NEXT_PUBLIC_SITE_URL"
step "Save."
printf '\n'
warn "ADD, do not replace. The old URI stays until stage 9 proves the new one"
warn "works. Google can take a few minutes to apply a change."
pause "Done? Press Enter."

# -- 6 ---------------------------------------------------------------------
stage "Xendit: re-point the payment webhook"
say "Payments are switched off today, so nothing breaks this minute - but an"
say "un-updated webhook means orders never reach 'paid' once they are on."
printf '\n'
open_url "https://dashboard.xendit.co/settings/developers#callbacks"
step "Find the invoice / payment-paid callback URL."
step "Set it to:"
say  "    $NEXT_PUBLIC_SITE_URL/api/webhooks/xendit"
step "Save."
printf '\n'
note "Return URLs need no change here - the app builds those in code from the"
note "origin you set in stage 4."
pause "Done? Press Enter."

# -- 7 ---------------------------------------------------------------------
stage "Xendit: fix the merchant display name"
say "The checkout page currently tells shoppers they are paying 'ndnpro'."
say "That is finding H2 in QA-REVIEW.md, still open."
printf '\n'
open_url "https://dashboard.xendit.co/settings/business-profile"
step "Change the business / merchant display name to: Yarns and Buttons"
step "Save."
printf '\n'
note "If your account keeps it elsewhere, look under Settings for the business"
note "profile or account name - the field you want is the one shown to"
note "shoppers on the hosted checkout page."
pause "Done? Press Enter."

# -- 8 ---------------------------------------------------------------------
stage "Redeploy production"
warn "NEXT_PUBLIC_* values are inlined at BUILD time, and sitemap.xml and"
warn "robots.txt are prerendered. Stage 4 changes nothing visible until a"
warn "fresh build runs."
printf '\n'
open_url "https://vercel.com/dashboard"
step "Project -> Deployments -> latest production deployment -> Redeploy."
step "Leave 'Use existing Build Cache' UNCHECKED so the new value is baked in."
step "Wait for it to finish before continuing."
pause "Deployment finished? Press Enter."

# -- 9 ---------------------------------------------------------------------
stage "Verify on the deployment, not on the notification"
_fail=0

step "Site responds..."
_code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 20 "$NEXT_PUBLIC_SITE_URL" 2>/dev/null || echo "000")
if [[ "$_code" == "200" ]]; then say "  -> HTTP 200"; else warn "  -> HTTP $_code (expected 200)"; _fail=1; fi

step "robots.txt advertises the new origin..."
_robots=$(curl -s --max-time 20 "$NEXT_PUBLIC_SITE_URL/robots.txt" 2>/dev/null || echo "")
if grep -q "$NEW_HOST" <<<"$_robots"; then say "  -> names $NEW_HOST"; else warn "  -> does NOT name $NEW_HOST"; _fail=1; fi
if grep -q "$OLD_HOST" <<<"$_robots"; then warn "  -> still names $OLD_HOST"; _fail=1; fi
if grep -q "localhost" <<<"$_robots"; then warn "  -> names localhost: that build resolved no origin"; _fail=1; fi

step "sitemap.xml carries the new origin..."
_sitemap=$(curl -s --max-time 25 "$NEXT_PUBLIC_SITE_URL/sitemap.xml" 2>/dev/null || echo "")
if grep -q "$NEW_HOST" <<<"$_sitemap"; then say "  -> names $NEW_HOST"; else warn "  -> does NOT name $NEW_HOST"; _fail=1; fi
if grep -q "$OLD_HOST" <<<"$_sitemap"; then warn "  -> still names $OLD_HOST"; _fail=1; fi

printf '\n'
if (( _fail )); then
  warn "Automated checks FAILED. The likeliest cause is the redeploy in stage 8"
  warn "reusing a cached build. Redeploy without the cache, then re-run this."
else
  say "Automated checks passed."
fi
printf '\n'
say "Two checks only you can make:"
step "Sign in with Google on the new host. It must complete, not error."
step "If payments are on, take a test payment and confirm it reaches 'paid'."
pause "Both verified? Press Enter."

# -- 10 --------------------------------------------------------------------
stage "Verify a preview link carries the new name"
say "Production has its own hostname, so stage 9 passing does not prove the"
say "preview URLs moved. Those are built from the account slug and the project"
say "name instead, which is why the rename reaches them at all."
printf '\n'
open_url "https://vercel.com/dashboard"
step "Project -> Deployments."
step "Open any deployment whose Environment is 'Preview' (not Production)."
note "No preview deployment listed? Push any branch other than master, wait"
note "for the build, then come back. A preview only exists once one is built."
step "Copy its full URL from the address bar or the Domains panel."
printf '\n'
ask PREVIEW_URL "Paste the preview URL (https://...):"
PREVIEW_URL="${PREVIEW_URL%/}"
PREVIEW_HOST="${PREVIEW_URL#https://}"
printf '\n'

_pfail=0
step "Preview host names the new account slug..."
if grep -q -- "-$NEW_USER\.vercel\.app" <<<"$PREVIEW_HOST"; then
  say "  -> ends in -$NEW_USER.vercel.app"
else
  warn "  -> does NOT end in -$NEW_USER.vercel.app"
  warn "     Stage 2's account rename did not take, or Vercel assigned a"
  warn "     different slug. Re-read the Username field before continuing."
  _pfail=1
fi

step "Preview host names the new project..."
if grep -q -- "^$NEW_PROJECT-" <<<"$PREVIEW_HOST"; then
  say "  -> starts with $NEW_PROJECT-"
else
  warn "  -> does NOT start with $NEW_PROJECT-"
  warn "     Either stage 3 did not take, or this preview was built BEFORE the"
  warn "     rename. Old previews keep their old URLs forever: trigger a fresh"
  warn "     build and check that one instead."
  _pfail=1
fi

step "Preview host no longer names the old identifiers..."
if grep -q -- "$OLD_USER\|$OLD_PROJECT" <<<"$PREVIEW_HOST"; then
  warn "  -> still contains '$OLD_USER' or '$OLD_PROJECT'"
  _pfail=1
else
  say "  -> clean"
fi

step "Preview responds..."
_code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 20 "$PREVIEW_URL" 2>/dev/null || echo "000")
case "$_code" in
  200) say "  -> HTTP 200" ;;
  401|403)
    say "  -> HTTP $_code: that is Deployment Protection, not a failure."
    note "     Previews are login-gated by default. The URL resolving at all is"
    note "     what this check is for; open it in your browser to see the page." ;;
  *) warn "  -> HTTP $_code (expected 200, or 401/403 if protection is on)"; _pfail=1 ;;
esac

printf '\n'
if (( _pfail )); then
  warn "Preview checks FAILED. Do NOT run stage 11 yet - it removes the"
  warn "rollback path. Fix the rename first, then re-run this wizard."
  confirm "Continue anyway?" || { say "Stopped before cleanup. Nothing was removed."; exit 1; }
else
  say "Preview links carry the new name."
fi
pause "Press Enter."

# -- 11 --------------------------------------------------------------------
stage "Clean up, only now that it is proven"
open_url "https://console.cloud.google.com/apis/credentials"
step "Remove the old redirect URI:"
say  "    https://$OLD_HOST/api/auth/callback/google"
step "Remove the old JavaScript origin:  https://$OLD_HOST"
printf '\n'
note "This is last on purpose - it was the rollback path if Google sign-in had"
note "failed in stage 9."
printf '\n'
say "Then, back in the repo and docs:"
step "Flip QA finding H2 to closed in update.md."
step "Update the deployment hostname in README.md, PRODUCT.md, and in"
step "F:\\Downloads\\Cro_md (Cro_Documentation.md status line and its §3 row)."
pause "Done? Press Enter."

finish
