#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=12

# ── Author helper (below the library marker, so it's fair game to edit) ────
# dns_check TYPE NAME [EXPECTED] — looks up a record and shows the answer,
# then lets the human retry (DNS is slow to propagate) or continue anyway.
# Uses `dig` when present, else `nslookup` (Git Bash / Windows has nslookup).
# Never fatal: propagation can outlast this sitting, and the record can be
# re-checked on a later run.
dns_check() {
  local rtype="$1" name="$2" expected="${3:-}" out=""
  while true; do
    printf '  %s… querying%s %s %s\n' "$DIM" "$RESET" "$rtype" "$name"
    if command -v dig >/dev/null 2>&1; then
      out=$(dig +short "$rtype" "$name" @1.1.1.1 2>/dev/null || true)
    else
      out=$(nslookup -type="$rtype" "$name" 1.1.1.1 2>/dev/null | sed -n '/Non-authoritative\|Name\|nameserver\|text\|exchanger\|mail/,$p' || true)
    fi
    if [[ -z "$out" ]]; then
      warn "no $rtype record visible yet for $name (DNS can take minutes to hours)."
    else
      printf '  %s✓ answer:%s\n' "$GREEN" "$RESET"
      printf '%s\n' "$out" | sed 's/^/      /'
      if [[ -n "$expected" ]]; then
        if printf '%s' "$out" | grep -qiF "$expected"; then
          printf '  %s✓ contains%s "%s"\n' "$GREEN" "$RESET" "$expected"
        else
          warn "answer does not yet contain \"$expected\" — likely still propagating."
        fi
      fi
    fi
    confirm "Re-check this record?" || break
  done
}

banner "Stage A — yarnsandbuttons.com domain, deliverability, and origin cutover"

# ── Preamble: order matters, and why ──────────────────────────────────────
stage "Before you start"
say "This moves yarnsandbuttons.com onto Cloudflare DNS, verifies it with Resend"
say "so mail actually leaves the building, points the site at the deployment, and"
say "flips the app's origin, sign-in and payment URLs to the new domain."
note "Order matters: nameservers first, then records, then Resend verify, then the"
note "app cutover. Each DNS step is checked with a live lookup before you move on."
warn "Merge PR #27 (the contact-address code) so it is LIVE on the same deploy as"
warn "the Vercel env change in Stage 10 — the address must not go public before mail"
warn "works. Do NOT deploy that PR earlier."
say ""
say "Have these tabs' logins ready: Cloudflare, Namecheap, Resend, Vercel,"
say "Google Cloud Console, Xendit."
pause "Press Enter when you're ready."

# ── 1. Cloudflare: add the site, read the nameservers ─────────────────────
stage "Cloudflare: add the site"
say "Create the zone so Cloudflare can manage DNS for the domain."
open_url "https://dash.cloudflare.com/?to=/:account/add-site"
step "Enter  yarnsandbuttons.com  and continue."
step "Choose the FREE plan."
step "Cloudflare imports existing records — keep the registrar's root MX and"
step "the root SPF TXT (the studio's email forwarding). Do not delete them."
step "On the 'Change your nameservers' screen it shows two nameservers"
step "(e.g. xxx.ns.cloudflare.com). Copy them."
ask CF_NS1 "First Cloudflare nameserver:"
ask CF_NS2 "Second Cloudflare nameserver:"
note "You'll enter these at the registrar next."

# ── 2. Namecheap: point nameservers at Cloudflare ─────────────────────────
stage "Namecheap: point nameservers at Cloudflare"
say "The domain's nameservers are still dns1/dns2.registrar-servers.com (Namecheap)."
open_url "https://ap.www.namecheap.com/domains/list/"
step "Open  yarnsandbuttons.com  → Domain tab → NAMESERVERS."
step "Switch to 'Custom DNS' and enter the two Cloudflare nameservers:"
say  "      $CF_NS1"
say  "      $CF_NS2"
step "Save. Propagation is usually minutes but can take hours."
pause "Press Enter once saved, then we'll check."
dns_check NS yarnsandbuttons.com "ns.cloudflare.com"
warn "Cloudflare also emails you when the zone goes active. Resend verification"
warn "below only works once the nameservers have moved — don't rush past this."

# ── 3. Vercel: add the domain, read the record target ─────────────────────
stage "Vercel: add the domain"
say "Attach the domain to the project so Vercel serves it and issues its cert."
open_url "https://vercel.com/dashboard"
step "Open the project → Settings → Domains → Add  yarnsandbuttons.com  (and www)."
step "Vercel shows the DNS records to create — an A record for the apex and a"
step "CNAME for www. Copy the exact values it shows (commonly A → 76.76.21.21"
step "and www CNAME → cname.vercel-dns.com, but use what Vercel tells you)."
ask VC_APEX_A "Apex A record value Vercel shows:"
ask VC_WWW_CNAME "www CNAME target Vercel shows:"

# ── 4. Cloudflare: apex + www records ─────────────────────────────────────
stage "Cloudflare: point apex + www at Vercel"
open_url "https://dash.cloudflare.com/"
step "Open the yarnsandbuttons.com zone → DNS → Records."
step "Add  A  @  → $VC_APEX_A   (Proxy status: DNS only — grey cloud)."
step "Add  CNAME  www  → $VC_WWW_CNAME   (Proxy status: DNS only — grey cloud)."
note "DNS-only (grey cloud) so Vercel terminates TLS and its cert issuance works."
pause "Press Enter once both are saved."
dns_check A yarnsandbuttons.com "$VC_APEX_A"

# ── 5. Resend: add the domain, reveal its records ─────────────────────────
stage "Resend: add the sending domain"
say "Resend gives you the SPF / DKIM / bounce records to publish in Cloudflare."
open_url "https://resend.com/domains"
step "Add domain  yarnsandbuttons.com  (region: pick the one nearest PH, e.g."
step "us-east-1 is fine). Resend shows a table of DNS records."
step "It scopes its SPF and bounce MX under a 'send' subdomain, so the studio's"
step "existing root MX/SPF are untouched — no merge, no collision."
step "Copy each record's value. You'll paste them into Cloudflare next."
ask RESEND_MX_HOST     "send  MX  value (e.g. feedback-smtp.<region>.amazonses.com):"
ask RESEND_SPF_TXT     "send  TXT (SPF) value (e.g. v=spf1 include:amazonses.com ~all):"
ask RESEND_DKIM_TXT    "resend._domainkey  TXT (DKIM) value (long p=... string):"
note "If Resend also lists a DMARC row you can use it in the next stage instead"
note "of the default below."

# ── 6. Cloudflare: Resend records ─────────────────────────────────────────
stage "Cloudflare: publish the Resend records"
open_url "https://dash.cloudflare.com/"
step "In the zone → DNS → Records, add all three (Proxy status: DNS only):"
say  "   MX    send                → $RESEND_MX_HOST   (priority as Resend shows, e.g. 10)"
say  "   TXT   send                → $RESEND_SPF_TXT"
say  "   TXT   resend._domainkey   → $RESEND_DKIM_TXT"
step "Leave the registrar's root MX and root SPF exactly as they are."
pause "Press Enter once all three are saved."
dns_check TXT resend._domainkey.yarnsandbuttons.com "p="
dns_check TXT send.yarnsandbuttons.com "spf1"

# ── 7. Cloudflare: DMARC at p=none ────────────────────────────────────────
stage "Cloudflare: DMARC (monitoring only)"
say "DMARC starts at p=none — it collects reports without risking delivery."
step "Add a TXT record in Cloudflare:"
say  "   TXT   _dmarc   → v=DMARC1; p=none; rua=mailto:hello@yarnsandbuttons.com"
note "Tighten to quarantine/reject only later, once the reports show what sends"
note "as the domain."
pause "Press Enter once saved."
dns_check TXT _dmarc.yarnsandbuttons.com "DMARC1"

# ── 8. Resend: verify ─────────────────────────────────────────────────────
stage "Resend: verify the domain"
open_url "https://resend.com/domains"
step "Open yarnsandbuttons.com and click 'Verify'. Every row should turn green."
step "If a row is still pending, DNS is still propagating — wait and re-verify;"
step "the records are correct if the lookups above passed."
if confirm "Are all Resend rows verified (green)?"; then
  say "Good — mail can now send from the domain."
else
  warn "Leave this open and come back; the app cutover below still works, but"
  warn "real mail won't deliver until Resend shows verified."
fi

# ── 9. Vercel: env vars + redeploy (the app cutover) ──────────────────────
stage "Vercel: set the origin, sender, notify address — then redeploy"
warn "Do this only when PR #27 is merged, so the new address and the working"
warn "domain go live together."
open_url "https://vercel.com/dashboard"
step "Project → Settings → Environment Variables (Production). Set:"
say  "   NEXT_PUBLIC_SITE_URL   = https://yarnsandbuttons.com"
say  "   EMAIL_FROM             = Yarns and Buttons <hello@yarnsandbuttons.com>"
say  "   STUDIO_NOTIFY_EMAIL    = hello@yarnsandbuttons.com"
step "Then Deployments → latest → ⋯ → Redeploy, and UNCHECK 'Use existing"
step "Build Cache'. The origin is inlined at build time, so a var change without"
step "a fresh build does nothing."
pause "Press Enter once the redeploy with a fresh cache has finished."
note "Verify on the deployment, not the notification:"
step "   curl -s https://yarnsandbuttons.com/robots.txt   → names the new host"
step "   the footer / contact / privacy / terms show hello@yarnsandbuttons.com"

# ── 10. Google OAuth: new redirect URI ────────────────────────────────────
stage "Google Cloud: add the new OAuth redirect URI"
say "Sign-in breaks the moment DNS points at the new origin unless Google knows it."
open_url "https://console.cloud.google.com/apis/credentials"
step "Open the OAuth 2.0 Client used for sign-in → Authorized redirect URIs."
step "ADD (do not remove the old one yet):"
say  "   https://yarnsandbuttons.com/api/auth/callback/google"
step "Save. Keep the old vercel.app URI until you're sure traffic has moved."
pause "Press Enter once saved."

# ── 11. Xendit: repoint webhook + return URLs ─────────────────────────────
stage "Xendit: move the webhook and return URLs to the new origin"
warn "A webhook left on the old origin means paid orders never reach 'paid' —"
warn "the quietest way to break payments. Do this as part of the cutover."
open_url "https://dashboard.xendit.co/settings/developers#webhooks"
step "Update the payment webhook URL to:"
say  "   https://yarnsandbuttons.com/api/webhooks/xendit"
step "Anywhere a success/failure return URL is configured, move it to the"
step "https://yarnsandbuttons.com origin as well."
step "Keep test mode as-is — going live is a separate, deliberate decision."
if confirm "Have you fired a Xendit TEST payment that reached 'paid' on the new origin?"; then
  say "Cutover verified end to end."
else
  warn "Do a real test-mode payment and confirm the order flips to 'paid' before"
  warn "calling Stage A done — this is the check that has been skipped twice before."
fi

finish
